print('Hello World')
print('corinthians é pequeno')
print('good morning')
print('Arcane is the greatest serie of all time')
print("Valorant is the best game")
print("palmeiras não tem mundial")
print('São Paulo campeão de tudo')
print('Iphone é pior que Android')
print('miojo da cançer ')
print("sushi é bom")
